package net.malus.halgvent.block;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroupEntries;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.malus.halgvent.Halgvent_Newlands;
import net.malus.halgvent.items.HalgventItems;
import net.minecraft.block.*;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;
import org.apache.commons.compress.compressors.lz77support.LZ77Compressor;

public class HalgventBlocks
{
    public static final Block SULFUR_BLOCK = registerBlock("sulfur_block", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block EXTRA_SULFUR_BLOCK = registerBlock("extra_sulfur_block", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TALK = registerBlock("talk", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CHALK = registerBlock("chalk", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SLATE = registerBlock("slate", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SLATE_TILES = registerBlock("slate_tiles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BLUE_SCHIST_COBBLE = registerBlock("blue_schist_cobble", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SCHIST_DWARVEN_COLUMN = registerBlock("schist_dwarven_column", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ASH = registerBlock("ash", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block AUTUMNAL_FOREST_FLOOR_WITH_ROOTS = registerBlock("autumnal_forest_floor_with_roots", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block AUTUMN_GRASS = registerBlock("autumn_grass", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BLACK_SAND = registerBlock("black_sand", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CYAN_CLAY = registerBlock("cyan_clay", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_FLOOR = registerBlock("mossy_floor", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSS_GREEN_FOREST = registerBlock("moss_green_forest", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSS_LIGHT_GREEN_FOREST = registerBlock("moss_light_green_forest", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSS_RED_TUNDRA = registerBlock("moss_red_tundra", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSS_YELLOW_TUNDRA = registerBlock("moss_yellow_tundra", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MUDDY_AUTUMNAL_FOREST_FLOOR = registerBlock("muddy_autumnal_forest_floor", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ORANGE_GRASS_SIDE = registerBlock("orange_grass_side", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block RED_CLAY = registerBlock("red_clay", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block RED_GRASS_SIDE = registerBlock("red_grass_side", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block RIVER_SAND = registerBlock("river_sand", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ROAD_SAND = registerBlock("road_sand", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SEA_SAND = registerBlock("sea_sand", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SMALL_STONES = registerBlock("small_stones", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TAIGA_FOREST_FLOOR = registerBlock("taiga_forest_floor", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TORF = registerBlock("torf", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_GRASS_TOP = registerBlock("yellow_grass_top", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ARGENT_ORE = registerBlock("argent_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ARGENT_ORE_GRANITE = registerBlock("argent_ore_granite", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block AURITE_ORE = registerBlock("aurite_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BOREALIRONZHILA = registerBlock("borealironzhila", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BOREAL_IRON_ORE = registerBlock("boreal_iron_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BROWN_IRON_ORE = registerBlock("brown_iron_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BROWN_IRON_ORE_GRANITE = registerBlock("brown_iron_ore_granite", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CASSITERITE_ORE = registerBlock("cassiterite_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CUPRITE_ORE = registerBlock("cuprite_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CUPRITE_ORE_GNEISS = registerBlock("cuprite_ore_gneiss", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CUPRITE_ORE_GRANITE = registerBlock("cuprite_ore_granite", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CUPRITE_ORE_LIMESTONE = registerBlock("cuprite_ore_limestone", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block DRAGON_IRON_ORE_GRANITE = registerBlock("dragon_iron_ore_granite", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block GALENITE_ORE = registerBlock("galenite_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block GALENITE_ORE_GRANITE = registerBlock("galenite_ore_granite", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block HALKOPIRIT_ORE = registerBlock("halkopirit_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block HALKOPIRIT_ORE_GNEISS = registerBlock("halkopirit_ore_gneiss", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block HALKOPIRIT_ORE_GRANITE = registerBlock("halkopirit_ore_granite", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block HALKOPIRIT_ORE_LIMESTONE = registerBlock("halkopirit_ore_limestone", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block KIANITE_ORE = registerBlock("kianite_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block KORUNDZHILA = registerBlock("korundzhila", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block LIMONITEZHILA = registerBlock("limonitezhila", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MAGNETITZHILA = registerBlock("magnetitzhila", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block RED_IRON_ORE = registerBlock("red_iron_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block RED_IRON_ORE_GNEISS = registerBlock("red_iron_ore_gneiss", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block RED_IRON_ORE_GRANITE = registerBlock("red_iron_ore_granite", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block RED_IRON_ORE_LIMESTONE = registerBlock("red_iron_ore_limestone", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TETRAEDITE_ORE = registerBlock("tetraedite_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TIN_CASSITERITE_ORE = registerBlock("tin_cassiterite_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TIN_TETRAEDIT_ORE = registerBlock("tin_tetraedit_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WULFRENITE_ORE = registerBlock("wulfrenite_ore", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block COPPER_BLOCK = registerBlock("copper_block", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CORRODED_ANCIENT_BLOCK = registerBlock("corroded_ancient_block", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CORRODED_ANCIENT_DOOR_LOWER = registerBlock("corroded_ancient_door_lower", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block COLUMN_OLD = registerBlock("column_old", new Block(FabricBlockSettings.copyOf(Blocks.OAK_DOOR).sounds(BlockSoundGroup.COPPER)));
    public static final Block MOSSY_CLAY_BRICK = registerBlock("mossy_clay_brick", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_CLAY_BRICK_TOPBOTTOM = registerBlock("mossy_clay_brick_topbottom", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block OLD_BRICKS1 = registerBlock("old_bricks1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BIRCH_WOOD_WINDOW = registerBlock("birch_wood_window", new Block(FabricBlockSettings.copyOf(Blocks.GLASS).sounds(BlockSoundGroup.GLASS).notSolid()));
    public static final Block GILDED_CARVED_BIRCH_WOOD = registerBlock("gilded_carved_birch_wood", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block HORIZONTALLY_CARVED_BIRCH_WOOD = registerBlock("horizontally_carved_birch_wood", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block LIGHT_BIRCH_WOOD_PLANKS = registerBlock("light_birch_wood_planks", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WALL_OF_BIRCH_LOGS_SIDE = registerBlock("wall_of_birch_logs_side", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BEECH_LOG = registerBlock("beech_log", new PillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_LOG).sounds(BlockSoundGroup.STONE)));
    public static final Block BEECH_WOOD_BEAM = registerBlock("beech_wood_beam", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BEECH_WOOD_BEAM_WALL = registerBlock("beech_wood_beam_wall", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BEECH_WOOD_PLANKS = registerBlock("beech_wood_planks", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_BEECH_LOG = registerBlock("mossy_beech_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block PEAR_LOG = registerBlock("pear_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block GILDED_CARVED_OAK_WOOD = registerBlock("gilded_carved_oak_wood", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block HORIZONTALLY_CARVED_OAK_WOOD = registerBlock("horizontally_carved_oak_wood", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block OAK_WOOD_BEAM_WALL = registerBlock("oak_wood_beam_wall", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block OAK_WOOD_TRELLIS = registerBlock("oak_wood_trellis", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CARVED_SPRUCE_WOOD = registerBlock("carved_spruce_wood", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block GILDED_CARVED_PINE_WOOD = registerBlock("gilded_carved_pine_wood", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block HORIZONTALLY_CARVED_SPRUCE_WOOD = registerBlock("horizontally_carved_spruce_wood", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_WILLOW_LOG = registerBlock("mossy_willow_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WILLOW_LOG = registerBlock("willow_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WILLOW_WOOD_BEAM = registerBlock("willow_wood_beam", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WILLOW_WOOD_PLANKS = registerBlock("willow_wood_planks", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WILLOW_WOOD_WALL = registerBlock("willow_wood_wall", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CEDAR_WOOD_WALL = registerBlock("cedar_wood_wall", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CEDER_LOG = registerBlock("ceder_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CEDER_NEEDLES = registerBlock("ceder_needles", new Block(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).sounds(BlockSoundGroup.STONE)));
    public static final Block LARCH_WOOD_BEAM = registerBlock("larch_wood_beam", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block LARCH_WOOD_PLANKS = registerBlock("larch_wood_planks", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ASPEN_LEAVES = registerBlock("aspen_leaves", new Block(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).sounds(BlockSoundGroup.STONE)));
    public static final Block ASPEN_LOG = registerBlock("aspen_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ASPEN_WOOD_BEAM = registerBlock("aspen_wood_beam", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ASPEN_WOOD_PLANKS = registerBlock("aspen_wood_planks", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ASPEN_WOOD_WALL = registerBlock("aspen_wood_wall", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block AUTUMNAL_ASPEN_LEAVES = registerBlock("autumnal_aspen_leaves", new Block(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_ASPEN_LOG = registerBlock("mossy_aspen_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block NORTHPINE_NEEDLES = registerBlock("northpine_needles", new Block(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).sounds(BlockSoundGroup.STONE)));
    public static final Block NORTHPINE_SPRUCE_LOG_SIDE = registerBlock("northpine_spruce_log_side", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block NORTHPINE_WOOD_BEAM = registerBlock("northpine_wood_beam", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block NORTHPINE_WOOD_PLANKS = registerBlock("northpine_wood_planks", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block NORTPINE_SPRUCE_WOOD_WALL = registerBlock("nortpine_spruce_wood_wall", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ORANGE_PINE_LOG = registerBlock("orange_pine_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block PINE_NEEDLES = registerBlock("pine_needles", new Block(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).sounds(BlockSoundGroup.STONE)));
    public static final Block PINE_WOOD_BEAM = registerBlock("pine_wood_beam", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block PINE_WOOD_BEAM_WALL = registerBlock("pine_wood_beam_wall", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block PINE_WOOD_PLANKS = registerBlock("pine_wood_planks", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block APPLE_LOG = registerBlock("apple_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block APPLE_TREE_LEAVES = registerBlock("apple_tree_leaves", new Block(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).sounds(BlockSoundGroup.STONE)));
    public static final Block APPLE_WOOD_BEAM = registerBlock("apple_wood_beam", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block APPLE_WOOD_PLANKS = registerBlock("apple_wood_planks", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_APPLE_LOG = registerBlock("mossy_apple_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ASH_LEAVES = registerBlock("ash_leaves", new Block(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).sounds(BlockSoundGroup.STONE)));
    public static final Block ASH_LOG = registerBlock("ash_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ASH_WOOD_BEAM = registerBlock("ash_wood_beam", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ASH_WOOD_BEAM_WALL = registerBlock("ash_wood_beam_wall", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ASH_WOOD_PLANKS = registerBlock("ash_wood_planks", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CARVED_ASH_WOOD_PILLAR = registerBlock("carved_ash_wood_pillar", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_ASH_LOG = registerBlock("mossy_ash_log", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BUNDLED_FIREWOOD = registerBlock("bundled_firewood", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block OLD_WICKER_FENCE = registerBlock("old_wicker_fence", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block REINFORCED_PLANKS = registerBlock("reinforced_planks", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block REINFORCED_WOODEN_TRAPDOOR_1 = registerBlock("reinforced_wooden_trapdoor_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WHITE_WOOD_BEAM_SIDE = registerBlock("white_wood_beam_side", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WHITE_WOOD_WALL = registerBlock("white_wood_wall", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block APPLE_TREE_SAPLING = registerBlock("apple_tree_sapling", new Block(FabricBlockSettings.copyOf(Blocks.OAK_SAPLING)));
    public static final Block ASH_TREE_SAPLING = registerBlock("ash_tree_sapling", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block ASH_TREE_SAPLING_TALL = registerBlock("ash_tree_sapling_tall", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block ASPEN_TREE_SAPLING = registerBlock("aspen_tree_sapling", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block ASPEN_TREE_SAPLING_TALL = registerBlock("aspen_tree_sapling_tall", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block BEECH_TREE_SAPLING = registerBlock("beech_tree_sapling", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block BEECH_TREE_SAPLING_TALL = registerBlock("beech_tree_sapling_tall", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block CEDER_TREE_SAPLING = registerBlock("ceder_tree_sapling", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block NORTHPINE_TREE_SAPLING = registerBlock("northpine_tree_sapling", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block PEAR_TREE_SAPLING = registerBlock("pear_tree_sapling", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block PINE_TREE_SAPLING = registerBlock("pine_tree_sapling", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block WILLOW_TREE_SAPLING = registerBlock("willow_tree_sapling", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block WILLOW_TREE_SAPLING_TALL = registerBlock("willow_tree_sapling_tall", new Block(FabricBlockSettings.copyOf(Blocks.ACACIA_SAPLING).sounds(BlockSoundGroup.STONE)));
    public static final Block PEAR_TREE_LEAVES = registerBlock("pear_tree_leaves", new Block(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).sounds(BlockSoundGroup.STONE)));
    public static final Block WEEPING_WILLOW_LEAVES = registerBlock("weeping_willow_leaves", new Block(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).sounds(BlockSoundGroup.STONE).notSolid()));
    public static final Block CLADDING_BRICK = registerBlock("cladding_brick", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block COLUMN_FR = registerBlock("column_fr", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block COLUMN_ORN = registerBlock("column_orn", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block FIRERESIST_BRICKS1 = registerBlock("fireresist_bricks1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block FIRERESIST_BRICKS2 = registerBlock("fireresist_bricks2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block FIRERESIST_BRICKS3 = registerBlock("fireresist_bricks3", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_RED_CLAY_BRICK = registerBlock("mossy_red_clay_brick", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_RED_CLAY_BRICK_TOPBOTTOM = registerBlock("mossy_red_clay_brick_topbottom", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_SMALL_BRICK = registerBlock("mossy_small_brick", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ORANGE_BRICKS1 = registerBlock("orange_bricks1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ORANGE_BRICKS2 = registerBlock("orange_bricks2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ORANGE_BRICKS3 = registerBlock("orange_bricks3", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ROMAN_CLAY_BRICK = registerBlock("roman_clay_brick", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SMALL_BRICK = registerBlock("small_brick", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block LIGHT_GRAY_PLASTER = registerBlock("light_gray_plaster", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TAN_STUCCO = registerBlock("tan_stucco", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WHITE_PLASTER = registerBlock("white_plaster", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WHITE_PLASTER_WITH_GREENRED_DRAW = registerBlock("white_plaster_with_greenred_draw", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WHITE_PLASTER_WITH_ORANGE_ORNAMENT = registerBlock("white_plaster_with_orange_ornament", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WHITE_PLASTER_WITH_RED_DRAW = registerBlock("white_plaster_with_red_draw", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WHITE_PLASTER_WITH_RED_ORNAMENT = registerBlock("white_plaster_with_red_ornament", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_PLASTER = registerBlock("yellow_plaster", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BROWN_THATCH = registerBlock("brown_thatch", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BROWN_THATCH_TOP = registerBlock("brown_thatch_top", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block DARK_BROWN_THATCH = registerBlock("dark_brown_thatch", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block DARK_BROWN_THATCH_TRACERY = registerBlock("dark_brown_thatch_tracery", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block DARK_YELLOW_THATCH = registerBlock("dark_yellow_thatch", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block DARK_YELLOW_THATCH_TOP = registerBlock("dark_yellow_thatch_top", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_BROWN_THATCH = registerBlock("mossy_brown_thatch", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_DARK_BROWN_THATCH = registerBlock("mossy_dark_brown_thatch", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_YELLOW_THATCH = registerBlock("mossy_yellow_thatch", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block OVERGROWN_MOSSY_DARK_BROWN_THATCH = registerBlock("overgrown_mossy_dark_brown_thatch", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_THATCH = registerBlock("yellow_thatch", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_THATCH_TOP = registerBlock("yellow_thatch_top", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BROWN_GRAY_WOOD_SHINGLES = registerBlock("brown_gray_wood_shingles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BROWN_WOOD_DIAMOND_SHINGLES = registerBlock("brown_wood_diamond_shingles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BROWN_WOOD_SHINGLES = registerBlock("brown_wood_shingles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block DARK_RED_DIAMOND_CLAY_SHINGLES = registerBlock("dark_red_diamond_clay_shingles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block DARK_RED_WOOD_DIAMOND_SHINGLES = registerBlock("dark_red_wood_diamond_shingles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block LIGHT_RED_CLAY_BEAVER_TAIL_TILES = registerBlock("light_red_clay_beaver_tail_tiles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MOSSY_RED_WOOD_DIAMOND_SHINGLES = registerBlock("mossy_red_wood_diamond_shingles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block OLD_WOOD_SHINGLES = registerBlock("old_wood_shingles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block RED_CLAY_BEAVER_TAIL_TILES = registerBlock("red_clay_beaver_tail_tiles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block RED_CLAY_TILES = registerBlock("red_clay_tiles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block RED_WOOD_DIAMOND_SHINGLES = registerBlock("red_wood_diamond_shingles", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TERRACOTTA_IMBRICES_AND_TEGULAE = registerBlock("terracotta_imbrices_and_tegulae", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block BLUE_TUDOR_BOX_FRAME = registerBlock("blue_tudor_box_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TUDOR_BOX_FRAME = registerBlock("tudor_box_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TUDOR_CROSS_FRAME = registerBlock("tudor_cross_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TUDOR_DIAGONAL_DOWNWARDS_FRAME = registerBlock("tudor_diagonal_downwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TUDOR_DIAGONAL_FRAME_1 = registerBlock("tudor_diagonal_frame_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TUDOR_DIAGONAL_FRAME_2 = registerBlock("tudor_diagonal_frame_2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TUDOR_DIAGONAL_UPWARDS_FRAME = registerBlock("tudor_diagonal_upwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TUDOR_NARROW_DIAGONAL_FRAMES_1 = registerBlock("tudor_narrow_diagonal_frames_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block TUDOR_NARROW_DIAGONAL_FRAMES_2 = registerBlock("tudor_narrow_diagonal_frames_2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CLAY_BRICK_WITH_TUDOR_BOX_FRAME = registerBlock("clay_brick_with_tudor_box_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CLAY_BRICK_WITH_TUDOR_CROSS_FRAME = registerBlock("clay_brick_with_tudor_cross_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CLAY_BRICK_WITH_TUDOR_DIAGONAL_DOWNWARDS_FRAME = registerBlock("clay_brick_with_tudor_diagonal_downwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CLAY_BRICK_WITH_TUDOR_DIAGONAL_FRAME_1 = registerBlock("clay_brick_with_tudor_diagonal_frame_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CLAY_BRICK_WITH_TUDOR_DIAGONAL_FRAME_2 = registerBlock("clay_brick_with_tudor_diagonal_frame_2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CLAY_BRICK_WITH_TUDOR_DIAGONAL_UPWARDS_FRAME = registerBlock("clay_brick_with_tudor_diagonal_upwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CLAY_BRICK_WITH_TUDOR_NARROW_DIAGONAL_FRAMES_1 = registerBlock("clay_brick_with_tudor_narrow_diagonal_frames_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block CLAY_BRICK_WITH_TUDOR_NARROW_DIAGONAL_FRAMES_2 = registerBlock("clay_brick_with_tudor_narrow_diagonal_frames_2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MUD_PLASTER_WITH_TUDOR_BOX_FRAME = registerBlock("mud_plaster_with_tudor_box_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MUD_PLASTER_WITH_TUDOR_CROSS_FRAME = registerBlock("mud_plaster_with_tudor_cross_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MUD_PLASTER_WITH_TUDOR_DIAGONAL_DOWNWARDS_FRAME = registerBlock("mud_plaster_with_tudor_diagonal_downwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MUD_PLASTER_WITH_TUDOR_DIAGONAL_FRAME_1 = registerBlock("mud_plaster_with_tudor_diagonal_frame_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MUD_PLASTER_WITH_TUDOR_DIAGONAL_FRAME_2 = registerBlock("mud_plaster_with_tudor_diagonal_frame_2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MUD_PLASTER_WITH_TUDOR_DIAGONAL_UPWARDS_FRAME = registerBlock("mud_plaster_with_tudor_diagonal_upwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MUD_PLASTER_WITH_TUDOR_NARROW_DIAGONAL_FRAMES_1 = registerBlock("mud_plaster_with_tudor_narrow_diagonal_frames_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block MUD_PLASTER_WITH_TUDOR_NARROW_DIAGONAL_FRAMES_2 = registerBlock("mud_plaster_with_tudor_narrow_diagonal_frames_2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SANDSTONE_WITH_TUDOR_BOX_FRAME = registerBlock("sandstone_with_tudor_box_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SANDSTONE_WITH_TUDOR_CROSS_FRAME = registerBlock("sandstone_with_tudor_cross_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SANDSTONE_WITH_TUDOR_DIAGONAL_DOWNWARDS_FRAME = registerBlock("sandstone_with_tudor_diagonal_downwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SANDSTONE_WITH_TUDOR_DIAGONAL_FRAME_1 = registerBlock("sandstone_with_tudor_diagonal_frame_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SANDSTONE_WITH_TUDOR_DIAGONAL_FRAME_2 = registerBlock("sandstone_with_tudor_diagonal_frame_2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SANDSTONE_WITH_TUDOR_DIAGONAL_UPWARDS_FRAME = registerBlock("sandstone_with_tudor_diagonal_upwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SANDSTONE_WITH_TUDOR_NARROW_DIAGONAL_FRAMES_1 = registerBlock("sandstone_with_tudor_narrow_diagonal_frames_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SANDSTONE_WITH_TUDOR_NARROW_DIAGONAL_FRAMES_2 = registerBlock("sandstone_with_tudor_narrow_diagonal_frames_2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block WATTLE_WITH_TUDOR_DIAGONAL_UPWARDS_FRAME = registerBlock("wattle_with_tudor_diagonal_upwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_PLASTER_WITH_TUDOR_BOX_FRAME = registerBlock("yellow_plaster_with_tudor_box_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_PLASTER_WITH_TUDOR_CROSS_FRAME = registerBlock("yellow_plaster_with_tudor_cross_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_PLASTER_WITH_TUDOR_DIAGONAL_DOWNWARDS_FRAME = registerBlock("yellow_plaster_with_tudor_diagonal_downwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_PLASTER_WITH_TUDOR_DIAGONAL_FRAME_1 = registerBlock("yellow_plaster_with_tudor_diagonal_frame_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_PLASTER_WITH_TUDOR_DIAGONAL_FRAME_2 = registerBlock("yellow_plaster_with_tudor_diagonal_frame_2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_PLASTER_WITH_TUDOR_DIAGONAL_UPWARDS_FRAME = registerBlock("yellow_plaster_with_tudor_diagonal_upwards_frame", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_PLASTER_WITH_TUDOR_NARROW_DIAGONAL_FRAMES_1 = registerBlock("yellow_plaster_with_tudor_narrow_diagonal_frames_1", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block YELLOW_PLASTER_WITH_TUDOR_NARROW_DIAGONAL_FRAMES_2 = registerBlock("yellow_plaster_with_tudor_narrow_diagonal_frames_2", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block DIAGONAL_SQUARE_PATTERN_GLASS_WINDOW = registerBlock("diagonal_square_pattern_glass_window", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block GOTHIC_WINDOW = registerBlock("gothic_window", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block ROUNDED_WINDOW = registerBlock("rounded_window", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SIMPLE_SQUARE_PATTERN_GLASS_WINDOW = registerBlock("simple_square_pattern_glass_window", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block SMALL_DIAMOND_PATTERN_GLASS_WINDOW = registerBlock("small_diamond_pattern_glass_window", new Block(FabricBlockSettings.copyOf(Blocks.COPPER_ORE).sounds(BlockSoundGroup.STONE)));
    public static final Block AUTUMNAL_BRACKEN = registerBlock("autumnal_bracken", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block BOLOTNIK = registerBlock("bolotnik", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block BOROVICHOK = registerBlock("borovichok", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block CHERNOBYLLINIK = registerBlock("chernobyllinik", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block DWARF_BIRCH = registerBlock("dwarf_birch", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block HEATHER = registerBlock("heather", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block IVANCHAY = registerBlock("ivanchay", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block KOVYL = registerBlock("kovyl", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block LAVENDER = registerBlock("lavender", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block LEBEDA = registerBlock("lebeda", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block LOBELIA_FLOWERS = registerBlock("lobelia_flowers", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block MUHOMOR = registerBlock("muhomor", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block NORTH_LICHEN = registerBlock("north_lichen", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block OMELA = registerBlock("omela", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block POGANKA = registerBlock("poganka", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block PUSHICA = registerBlock("pushica", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block RAZRYV_TRAVA = registerBlock("razryv_trava", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block RED_SPHAGNUM = registerBlock("red_sphagnum", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block SPHAGNUM = registerBlock("sphagnum", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));
    public static final Block WOLFSBANE = registerBlock("wolfsbane", new Block(FabricBlockSettings.copyOf(Blocks.SHORT_GRASS).sounds(BlockSoundGroup.STONE)));

    private static Block registerBlock(String name, Block block)
    {
        registerBlockItem(name,block);
        return  Registry.register(Registries.BLOCK, new Identifier(Halgvent_Newlands.MOD_ID, name), block);
    }
    private static Item registerBlockItem(String name, Block block)
    {
        return Registry.register(Registries.ITEM, new Identifier(Halgvent_Newlands.MOD_ID, name), new BlockItem(block, new FabricItemSettings()));
    }
    public static void registerHalgventBlocks()
    {

        Halgvent_Newlands.LOGGER.info("Registering blocks for " + Halgvent_Newlands.MOD_ID);
    }
}
