package net.malus.halgvent.block;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.malus.halgvent.Halgvent_Newlands;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class WoodItemGroup
{
    public static final ItemGroup Wood_Group = Registry.register(Registries.ITEM_GROUP, new Identifier(Halgvent_Newlands.MOD_ID, "woods"), FabricItemGroup.builder().displayName(Text.translatable("itemgroup.woods")).icon(() -> new ItemStack(HalgventBlocks.BIRCH_WOOD_WINDOW)).entries((displayContext, entries) ->
            {
                entries.add(HalgventBlocks.BIRCH_WOOD_WINDOW);
                entries.add(HalgventBlocks.WALL_OF_BIRCH_LOGS_SIDE);
                entries.add(HalgventBlocks.GILDED_CARVED_BIRCH_WOOD);
                entries.add(HalgventBlocks.HORIZONTALLY_CARVED_BIRCH_WOOD);
                entries.add(HalgventBlocks.LIGHT_BIRCH_WOOD_PLANKS);
                entries.add(HalgventBlocks.BEECH_LOG);
                entries.add(HalgventBlocks.BEECH_WOOD_BEAM);
                entries.add(HalgventBlocks.BEECH_WOOD_BEAM_WALL);
                entries.add(HalgventBlocks.BEECH_WOOD_PLANKS);
                entries.add(HalgventBlocks.MOSSY_BEECH_LOG);
                entries.add(HalgventBlocks.PEAR_LOG);
                entries.add(HalgventBlocks.GILDED_CARVED_OAK_WOOD);
                entries.add(HalgventBlocks.HORIZONTALLY_CARVED_OAK_WOOD);
                entries.add(HalgventBlocks.OAK_WOOD_BEAM_WALL);
                entries.add(HalgventBlocks.OAK_WOOD_TRELLIS);
                entries.add(HalgventBlocks.CARVED_SPRUCE_WOOD);
                entries.add(HalgventBlocks.GILDED_CARVED_PINE_WOOD);
                entries.add(HalgventBlocks.HORIZONTALLY_CARVED_SPRUCE_WOOD);
                entries.add(HalgventBlocks.MOSSY_WILLOW_LOG);
                entries.add(HalgventBlocks.WILLOW_LOG);
                entries.add(HalgventBlocks.WILLOW_WOOD_BEAM);
                entries.add(HalgventBlocks.WILLOW_WOOD_PLANKS);
                entries.add(HalgventBlocks.WILLOW_WOOD_WALL);
                entries.add(HalgventBlocks.CEDAR_WOOD_WALL);
                entries.add(HalgventBlocks.CEDER_LOG);
                entries.add(HalgventBlocks.CEDER_NEEDLES);
                entries.add(HalgventBlocks.LARCH_WOOD_BEAM);
                entries.add(HalgventBlocks.LARCH_WOOD_PLANKS);
                entries.add(HalgventBlocks.ASPEN_LEAVES);
                entries.add(HalgventBlocks.ASPEN_LOG);
                entries.add(HalgventBlocks.ASPEN_WOOD_BEAM);
                entries.add(HalgventBlocks.ASPEN_WOOD_PLANKS);
                entries.add(HalgventBlocks.ASPEN_WOOD_WALL);
                entries.add(HalgventBlocks.AUTUMNAL_ASPEN_LEAVES);
                entries.add(HalgventBlocks.MOSSY_ASPEN_LOG);
                entries.add(HalgventBlocks.NORTHPINE_NEEDLES);
                entries.add(HalgventBlocks.NORTHPINE_SPRUCE_LOG_SIDE);
                entries.add(HalgventBlocks.NORTHPINE_WOOD_BEAM);
                entries.add(HalgventBlocks.NORTHPINE_WOOD_PLANKS);
                entries.add(HalgventBlocks.NORTPINE_SPRUCE_WOOD_WALL);
                entries.add(HalgventBlocks.ORANGE_PINE_LOG);
                entries.add(HalgventBlocks.PINE_NEEDLES);
                entries.add(HalgventBlocks.PINE_WOOD_BEAM);
                entries.add(HalgventBlocks.PINE_WOOD_BEAM_WALL);
                entries.add(HalgventBlocks.PINE_WOOD_PLANKS);
                entries.add(HalgventBlocks.APPLE_LOG);
                entries.add(HalgventBlocks.APPLE_TREE_LEAVES);
                entries.add(HalgventBlocks.APPLE_WOOD_BEAM);
                entries.add(HalgventBlocks.APPLE_WOOD_PLANKS);
                entries.add(HalgventBlocks.MOSSY_APPLE_LOG);
                entries.add(HalgventBlocks.ASH_LEAVES);
                entries.add(HalgventBlocks.ASH_LOG);
                entries.add(HalgventBlocks.ASH_WOOD_BEAM);
                entries.add(HalgventBlocks.ASH_WOOD_BEAM_WALL);
                entries.add(HalgventBlocks.ASH_WOOD_PLANKS);
                entries.add(HalgventBlocks.CARVED_ASH_WOOD_PILLAR);
                entries.add(HalgventBlocks.MOSSY_ASH_LOG);
                entries.add(HalgventBlocks.BUNDLED_FIREWOOD);
                entries.add(HalgventBlocks.OLD_WICKER_FENCE);
                entries.add(HalgventBlocks.REINFORCED_PLANKS);
                entries.add(HalgventBlocks.REINFORCED_WOODEN_TRAPDOOR_1);
                entries.add(HalgventBlocks.WHITE_WOOD_BEAM_SIDE);
                entries.add(HalgventBlocks.WHITE_WOOD_WALL);
                entries.add(HalgventBlocks.APPLE_TREE_SAPLING);
                entries.add(HalgventBlocks.ASH_TREE_SAPLING);
                entries.add(HalgventBlocks.ASH_TREE_SAPLING_TALL);
                entries.add(HalgventBlocks.ASPEN_TREE_SAPLING);
                entries.add(HalgventBlocks.ASPEN_TREE_SAPLING_TALL);
                entries.add(HalgventBlocks.BEECH_TREE_SAPLING);
                entries.add(HalgventBlocks.BEECH_TREE_SAPLING_TALL);
                entries.add(HalgventBlocks.CEDER_TREE_SAPLING);
                entries.add(HalgventBlocks.NORTHPINE_TREE_SAPLING);
                entries.add(HalgventBlocks.PEAR_TREE_SAPLING);
                entries.add(HalgventBlocks.PINE_TREE_SAPLING);
                entries.add(HalgventBlocks.WILLOW_TREE_SAPLING);
                entries.add(HalgventBlocks.WILLOW_TREE_SAPLING_TALL);
                entries.add(HalgventBlocks.PEAR_TREE_LEAVES);
                entries.add(HalgventBlocks.WEEPING_WILLOW_LEAVES);
                entries.add(HalgventBlocks.BROWN_THATCH);
                entries.add(HalgventBlocks.BROWN_THATCH_TOP);
                entries.add(HalgventBlocks.DARK_BROWN_THATCH);
                entries.add(HalgventBlocks.DARK_BROWN_THATCH_TRACERY);
                entries.add(HalgventBlocks.DARK_YELLOW_THATCH);
                entries.add(HalgventBlocks.DARK_YELLOW_THATCH_TOP);
                entries.add(HalgventBlocks.MOSSY_BROWN_THATCH);
                entries.add(HalgventBlocks.MOSSY_DARK_BROWN_THATCH);
                entries.add(HalgventBlocks.MOSSY_YELLOW_THATCH);
                entries.add(HalgventBlocks.OVERGROWN_MOSSY_DARK_BROWN_THATCH);
                entries.add(HalgventBlocks.YELLOW_THATCH);
                entries.add(HalgventBlocks.YELLOW_THATCH_TOP);
                entries.add(HalgventBlocks.DIAGONAL_SQUARE_PATTERN_GLASS_WINDOW);
                entries.add(HalgventBlocks.GOTHIC_WINDOW);
                entries.add(HalgventBlocks.ROUNDED_WINDOW);
                entries.add(HalgventBlocks.SIMPLE_SQUARE_PATTERN_GLASS_WINDOW);
                entries.add(HalgventBlocks.SMALL_DIAMOND_PATTERN_GLASS_WINDOW);
                entries.add(HalgventBlocks.AUTUMNAL_BRACKEN);
                entries.add(HalgventBlocks.BOLOTNIK);
                entries.add(HalgventBlocks.BOROVICHOK);
                entries.add(HalgventBlocks.CHERNOBYLLINIK);
                entries.add(HalgventBlocks.DWARF_BIRCH);
                entries.add(HalgventBlocks.HEATHER);
                entries.add(HalgventBlocks.IVANCHAY);
                entries.add(HalgventBlocks.KOVYL);
                entries.add(HalgventBlocks.LAVENDER);
                entries.add(HalgventBlocks.LEBEDA);
                entries.add(HalgventBlocks.LOBELIA_FLOWERS);
                entries.add(HalgventBlocks.MUHOMOR);
                entries.add(HalgventBlocks.NORTH_LICHEN);
                entries.add(HalgventBlocks.OMELA);
                entries.add(HalgventBlocks.POGANKA);
                entries.add(HalgventBlocks.PUSHICA);
                entries.add(HalgventBlocks.RAZRYV_TRAVA);
                entries.add(HalgventBlocks.RED_SPHAGNUM);
                entries.add(HalgventBlocks.SPHAGNUM);
                entries.add(HalgventBlocks.WOLFSBANE);

            }
    ).build());
    public static void registerWoodGroup()
    {
        Halgvent_Newlands.LOGGER.info("Registering Wood Item Group for " + Halgvent_Newlands.MOD_ID);
    }
}
